name: Deploy
on:
  release:
    types: [published]

jobs:
  wordpress:
    name: WordPress.org
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Debugging
      run: |
        php --version
        svn --version

    - name: Install dependencies
      run: |
        npm install

    - name: Deploy
      run: npm run deploy:ci
      env:
        WPORG_PASSWORD: ${{ secrets.WPORG_PASSWORD }}
